version: '3'

services:

    docker-mysql:
        image: mysql
        container_name: joboonja
        environment:
            MYSQL_ROOT_PASSWORD: taha1234
            MYSQL_DATABASE: joboonja


    spring-app:
        restart: always
        image: ie-project/joboonja

        expose:
             - "8080"
        depends_on:
             - docker-mysql


    react-app:

