version: '3'

services:

    docker-mysql:
        image: mysql
        container_name: database
        environment:
            MYSQL_ROOT_PASSWORD: taha1234
            MYSQL_DATABASE: joboonja


    spring-app:
        restart: always
        container_name: backend
        image: ie-project/joboonja

        expose:
             - "8080"
        depends_on:
             - docker-mysql


    react-app:
        container_name: frontend
        build:
            context: ../IE-Front/.
            dockerfile: ../IE-Front/Dockerfile
        ports:
            - '3001:3000'

        volumes:
            - '.:/app'
            - '/app/node_modules'
#            environment:
#                - NODE_ENV=development
        depends_on:
          - spring-app






