version: '3'

services:

    docker-mysql:
        image: mysql
        container_name: database
        environment:
            MYSQL_ROOT_PASSWORD: taha1234
            MYSQL_DATABASE: joboonja


    spring-app:
        restart: always
        container_name: backend
        image: ie-project/joboonja

        expose:
             - "8080"
        depends_on:
             - docker-mysql


    react-app:
        build:
          ../IE-Front
        expose:
            - "3000"
        ports:
            - 3000:3000
        links:
            - spring-app
        command:
            npm run start






